# Generated by Django 5.2.6 on 2025-09-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadpage', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
